### ISSUE TITLE
Validate interaction between Gloo Mesh config and user-provided underlying config

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1086]
**Is your feature request related to a problem? Please describe.**
Users might want to provide underlying mesh (e.g. Istio) config in addition to Gloo Mesh config. Use cases include migrating to Gloo Mesh from a directly configured service mesh, or the use of mesh-specific config to produce some behavior not currently expose by the Gloo Mesh API.

**Describe the solution you'd like**
We should validate that Gloo Mesh is capable of "playing nicely" with user-provided underlying mesh configuration. Areas of concern include conflicting configuration and excess config produced by automated processes within Gloo Mesh that may be redundant with user-provided configuration.

**Comment by harveyxia** [comment]
After some discussion we arrived at a solution involving adding a toggle to the Settings CRD which allows users to turn on detection/reporting of translation of intersecting config—instead of outputting the intersecting config, networking will report the error back to the offending traffic policy.

For Istio, intersecting config refers to VirtualServices and DestinationRules that target hosts already being configured by externally provided VirtualServices or DestinationRules.
