### ISSUE TITLE
unable to verify fips

### ISSUE THREAD

**Issue by anandkumarpatel** [solo-io/gloo-mesh#1880]
**Describe the bug**
`goversion` no longer shows fips version like the documentation suggests: https://docs.solo.io/gloo-mesh/latest/setup/istio_fips/
```
$goversion -crypto /tmp/pilot-discovery
/tmp/pilot-discovery unknown Go version
```
**To Reproduce**
Use this dockerfile 
```
FROM golang:1.16
COPY --from=gcr.io/istio-enterprise/pilot:1.10.2-fips@sha256:581c5ce17735b8311c306fd7d6b29dd1ef27fd30b5247e807ed1215d35bab4ce /usr/local/bin/pilot-discovery /tmp/pilot-discovery
RUN go get github.com/rsc/goversion
RUN goversion -crypto /tmp/pilot-discovery
```
then build and run the command
```
docker build -t test .
docker run -it test goversion -crypto /tmp/pilot-discovery
```

**Expected behavior**
Expect to see `/tmp/pilot-discovery go1.14.12b4 (boring crypto)` like the documentation states
https://docs.solo.io/gloo-mesh/latest/setup/istio_fips/

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Mesh version
1.1.1
- Kubernetes version
-n/a

**Comment by jahvon** [comment]
This issue is actually due to a bug with `goversion` (see https://github.com/rsc/goversion/issues/14) - essentially it doesn't work with go versions 1.14+. You could just drop the use of goversion with something like:
```
FROM golang:1.16
COPY --from=gcr.io/istio-enterprise/pilot:1.10.2-fips@sha256:581c5ce17735b8311c306fd7d6b29dd1ef27fd30b5247e807ed1215d35bab4ce /usr/local/bin/pilot-discovery /tmp/pilot-discovery
```
and then run 
```
docker build -t test .
docker run -it test go version /tmp/pilot-discovery
```

The output I got was `/tmp/pilot-discovery: go1.16.4b7` - it doesn't explicitly have that boring crypto tag that `goversion` provides but the Go version includes the "b" followed by the crypto version as specified [here](https://go.googlesource.com/go/+/refs/heads/dev.boringcrypto.go1.12/misc/boring/). We should update our docs though.

**Comment by rvennam** [comment]
@christian-posta - your blog needs this update as well

**Comment by christian-posta** [comment]
Yeah good catch. Will update to point to this issue.

**Comment by anandkumarpatel** [comment]
Thank you for the info!
