### ISSUE TITLE
repor Write errors to the input resources that manage the output resource

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo-mesh#872]
**Is your feature request related to a problem? Please describe.**

When a user config object is invalid, its status is updated with an error. However, if a user config object is valid but writing the translated object fails, the error is only logged and not reported back to the crd status.

**Describe the solution you'd like**

Write errors should be written back to the status of each CRD that was responsible for writing the translated object.

**Additional context**

The `output.Snapshot.Apply()` methods accept an `errHandler` which can be used to handle write errors when individual output objects fail to write to the cluster: https://github.com/solo-io/service-mesh-hub/blob/merge-repos/pkg/api/networking.smh.solo.io/output/snapshot.go#L62

**Comment by ryantking** [comment]
Adding some more information here after diving into this with @harveyxia and @ilackarms.

Two things need to happen in order to get the desired functionality.

1. Parent resources to a resource need to be tracked. This can be done in memory, but doing it via an annotation is more desirable since that information will be useful in other circumstances.
2. Create an error handler that can find the parent(s) in the input snapshot and update their statuses with any error.
