### ISSUE TITLE
Migrate release CI from GCP Cloudbuild to Github Workflows

### ISSUE THREAD

**Issue by harveyxia** [solo-io/gloo-mesh#884]
Currently we depend on cloudbuild for publishing release assets (i.e. push Docker images, publish Helm charts to GCS, upload github release assets). There is no dependency between the cloudbuild workflow and the e2e Github workflow. We currently perform this check manually by only cutting a release after the main branch builds successfully.

By moving to Github workflow for publishing release artifacts, we can automate this dependency as well as make our CI uniform to github workflows.

**Comment by joekelley** [comment]
Via https://github.com/solo-io/service-mesh-hub/pull/890#issuecomment-690293072: "Closing because we'll stick with cloudbuild for now given that the build bot depends on that, and it's responsible for collating the changelogs into the release notes"

Keeping this open because I think the reasoning put forth in this issue description is sound. We should find or implement a github action that can publish release notes.

**Comment by joekelley** [comment]
Done in https://github.com/solo-io/gloo-mesh/pull/1352
